---
version: 1.0
root: "./.tests/cloud_test/"
timeout: 10000
shuffle-enabled: true
statistics:
  enabled: true
  interval: 60
import:
  - gke/.*
  - aks/.*
  - aws/.*
  - packet/.*
  - tests.yaml
reporting:
  junit-report: "results/junit.xml"
